default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: jroque
  password: fanvault
  host: localhost

development:
  <<: *default
  database: fanvault_development

test:
  <<: *default
  database: fanvault_test

production:
  <<: *default
  database: fanvault_production
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
